### ISSUE TITLE
[Feature Request] Customize Available Scopes (RDT-581)

### ISSUE THREAD

**Issue by hfudev** [espressif/conventional-precommit-linter#7]
Have an optional CLI args to customize all the available scopes

`--scopes foo bar` means

- `fix(foo): ...` is valid
- `feat(bar): ...` is valid
- `feat(unknown): ...` is invalid

If we don't set the known scopes, it could be an arbitrary value

- `fix(anything): ...` is valid

**Comment by tomassebestik** [comment]
@hfudev Thank you for your suggestion. I didn't know that some users would also like to have the scope limited to a specific expression, but perhaps in some cases this could be useful.

I think it's not hard to add it here, but then we need to add it to Danger check as well (so that the same configurations are in both tools). Let me check how it can be done.

**Comment by hfudev** [comment]
Thank you @tomassebestik

Here's one example from angular, they're limiting the supported scopes. https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#scope

I came up with the same idea when integrating your project to pytest-embedded. Since `scope` would be recorded in the changelog, it seems useful to me to limit the choices :)
